### ISSUE TITLE
BotvBot

### ISSUE THREAD

**Issue by oludom** [oludom/splitX#7]
Crash bei "BoardFull" ohne Gewinner, ein Stein fehlt (dim: 6)

**Comment by z0rsin** [comment]
Ursache ist eine Fenster mit showAndWait():
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:328)
	at ui.BasicUIX.startBot(BasicUIX.java:324)
	at ui.BasicUIX.access$900(BasicUIX.java:26)
	at ui.BasicUIX$9.handle(BasicUIX.java:302)
	at ui.BasicUIX$9.handle(BasicUIX.java:299)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)

**Comment by z0rsin** [comment]
Es wurden Steine mit ungültigen Positionen abgespeichert, aber nicht angezeigt. Diese sorgten, dafür dass das Board als Full erkannt wurde aber nicht so aussah.
Exception mit Platform.runLater behoben.
BoardFullException imlementiert, Fehler in der BoardPoint Klasse behoben siehe Issue #8
